import {emailConfig,deliverEmail} from './email.mjs';
import {money,required,uuid,reference,imageType,csv,effectiveStatus,hash,tokenFor,occupiedStatuses} from './core.mjs';
const env=(k:string)=>Deno.env.get(k)||'';
const base=env('SUPABASE_URL'),key=env('SUPABASE_SERVICE_ROLE_KEY');
const site=env('SITE_URL')||'https://shainetesting.netlify.app';
const headers={apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};
async function db(path:string,method='GET',body?:unknown){if(method==='GET'&&!path.includes('limit=')){let all:any[]=[];for(let offset=0;;offset+=500){const rows=await db(path+(path.includes('?')?'&':'?')+`limit=500&offset=${offset}`);all=all.concat(rows);if(rows.length<500)return all;}}const r=await fetch(`${base}/rest/v1/${path}`,{method,headers:{...headers,Prefer:'return=representation'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json().catch(()=>null);if(!r.ok){if(data?.code==='23505')throw Error('This entry or verified payment reference already exists');throw Error(data?.message||'Database request failed');}return data;}
const rpc=(name:string,body={})=>db(`rpc/drvn_${name}`,'POST',body);
const one=async(table:string,filter:string)=>{const rows=await db(`drvn_${table}?${filter}`);if(!rows?.length)throw Error('Record not found');return rows[0];};
async function admin(req:Request){const bearer=req.headers.get('Authorization')||'';if(!bearer.startsWith('Bearer '))throw Error('Admin sign-in required');const r=await fetch(`${base}/auth/v1/user`,{headers:{apikey:env('SUPABASE_ANON_KEY')||key,Authorization:bearer}});if(!r.ok)throw Error('Admin session expired');const u=await r.json();if(!(await db(`drvn_admins?user_id=eq.${u.id}`)).length)throw Error('Admin access required');return u.id;}
async function registration(token:string){if(!/^[a-f0-9]{64}$/.test(token||''))throw Error('Invalid status link');return one('registrations',`token_hash=eq.${await hash(token)}`);}
async function limited(req:Request,scope:string){const ip=req.headers.get('x-forwarded-for')?.split(',')[0]||'unknown';if(!await rpc('limit',{p_key:await hash(scope+ip)}))throw Error('Too many attempts. Please try again in an hour.');}
async function upload(file:any,bucket:string,prefix:string){if(!file?.data||file.data.length>2800000)throw Error('Choose an image smaller than 2 MB');let bytes;try{bytes=Uint8Array.from(atob(file.data),(c)=>c.charCodeAt(0));}catch{throw Error('Invalid image');}if(bytes.length>2097152)throw Error('Choose an image smaller than 2 MB');const [type,ext]=imageType(bytes);const path=`${prefix}/${crypto.randomUUID()}.${ext}`;const r=await fetch(`${base}/storage/v1/object/${bucket}/${path}`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':type},body:bytes});if(!r.ok)throw Error('Image upload failed');return path;}
async function notify(){if(!emailConfig(env).configured)return {configured:false};const jobs=await rpc('claim_emails');let sent=0;for(const job of jobs){try{const r=await one('registrations',`id=eq.${job.registration_id}`),c=await one('categories',`id=eq.${r.category_id}`),t=await one('tournaments',`id=eq.${c.tournament_id}`);const token=await tokenFor(r.idempotency_key,env('STATUS_TOKEN_SECRET')||key);const labels:any={payment_verified:'Payment received — your entry is confirmed',payment_submitted:'Payment proof received — awaiting review',payment_rejected:'Payment could not be verified',payment_correction_requested:'Payment details need correction',entry_confirmed:'Your entry is confirmed',registration_received:'Registration received',entry_promote:'A tournament slot is available for you',entry_cancel:'Your entry was cancelled',entry_refund:'Your refund has been recorded',event_cancelled:'Tournament cancelled'};const subject=labels[job.kind]||'Your tournament registration';const text=`Hi ${r.player_name},\n\n${subject}.\n${t.title} · ${c.name}\nRegistration: ${r.id}\nCurrent entry status: ${effectiveStatus(r).replaceAll('_',' ')}\nPayment status: ${r.payment_status.replaceAll('_',' ')}\n${job.note?`\nOrganizer note: ${job.note}\n`:''}\nView details and payment instructions using your private link:\n${site}/status.html#${token}\n\nKeep this link private.\nThe DRVN · Pickleball Davao`;const providerId=await deliverEmail(env,{to:r.email,subject:`The DRVN: ${subject}`,text,id:job.id});await db(`drvn_email_queue?id=eq.${job.id}`,'PATCH',{status:'sent',sent_at:new Date().toISOString(),provider_id:providerId,last_error:''});sent++;}catch(e){await db(`drvn_email_queue?id=eq.${job.id}`,'PATCH',{status:'failed',last_error:String(e.message).slice(0,300)});}}return {configured:true,sent};}
async function statusData(token:string){const r=await registration(token),c=await one('categories',`id=eq.${r.category_id}`),t=await one('tournaments',`id=eq.${c.tournament_id}`);const payments=await db(`drvn_payments?registration_id=eq.${r.id}&select=reference,amount_cents,status,review_reason,created_at&order=created_at.desc`);const emails=await db(`drvn_email_queue?registration_id=eq.${r.id}&select=kind,status,created_at&order=created_at.desc&limit=10`);return {id:r.id,player_name:r.player_name,email:r.email,partner_name:r.partner_name,amount_due:r.amount_due,status:effectiveStatus(r),payment_status:r.payment_status,expires_at:r.expires_at,settings:r.settings_snapshot,category:c.name,tournament:t,unit:r.unit,payments,emails};}
function safeURL(v:string){if(v&&!v.startsWith(`${base}/storage/v1/object/public/drvn-photos/`)&&!/^\/assets\/[a-z]+\.jpg$/.test(v))throw Error('Choose an uploaded event image');return v;}
async function route(req:Request,body:any){const action=body.action;
if(action==='events'){const events=await db('drvn_tournaments?status=in.(published,closed,completed,cancelled)&order=featured.desc,starts_at.asc');const cats=await db('drvn_categories?active=eq.true');const regs=await db('drvn_registrations?select=category_id,status,expires_at');return events.map((t:any)=>({...t,categories:cats.filter((c:any)=>c.tournament_id===t.id).map((c:any)=>({...c,available:Math.max(0,c.capacity-regs.filter((r:any)=>r.category_id===c.id&&occupiedStatuses.includes(effectiveStatus(r))).length)}))}));}
if(action==='register'){await limited(req,'register');const email=required(body.email,200).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Enter a valid email address');if(body.consent!==true)throw Error('Consent is required');const id=uuid(body.key),token=await tokenFor(id,env('STATUS_TOKEN_SECRET')||key);const r=await rpc('register',{p_category:uuid(body.category),p_name:required(body.name,100),p_email:email,p_partner:String(body.partner||'').trim().slice(0,100),p_key:id,p_token_hash:await hash(token),p_waitlist:body.waitlist===true});return {token,status:r.status};}
if(action==='status'){await limited(req,'status');return statusData(body.token);}
if(action==='payment'){await limited(req,'payment');const r=await registration(body.token);const ref=reference(body.reference),amount=money(body.amount);if(amount<=0)throw Error('Enter the paid amount');const paid=new Date(body.paid_at);if(!Number.isFinite(+paid)||+paid>Date.now()+300000)throw Error('Check the payment date');const sender=required(body.sender,100);if(['verified','refunded','submitted'].includes(r.payment_status)||['cancelled','waitlisted','confirmed'].includes(r.status))throw Error('This entry cannot accept another payment proof');const path=await upload(body.file,'drvn-receipts',r.id);try{await rpc('submit_payment',{p_registration:r.id,p_reference:ref,p_amount:amount,p_paid_at:paid.toISOString(),p_sender:sender,p_path:path});}catch(e){await fetch(`${base}/storage/v1/object/drvn-receipts`,{method:'DELETE',headers,body:JSON.stringify({prefixes:[path]})});throw e;}return {submitted:true};}
const actor=await admin(req);
if(action==='dashboard'){await rpc('expire');const names=['tournaments','categories','registrations','payments','settings','email_queue','audit'];const values=await Promise.all(names.map(n=>db(`drvn_${n}?${n==='audit'?'order=created_at.desc&limit=200':n==='registrations'?'select=id,category_id,player_name,email,partner_name,amount_due,unit,status,payment_status,expires_at,created_at':'select=*'}`)));return {...Object.fromEntries(names.map((n,i)=>[n,values[i]])),emailConfigured:emailConfig(env).configured,actor};}
if(action==='save_event'){const e=body.event;required(e.title,150);for(const k of ['description','rules','address','venue'])if(String(e[k]||'').length>10000)throw Error('Text is too long');safeURL(e.cover_url||'');for(const url of e.gallery||[])safeURL(url);if(!Array.isArray(e.gallery)||e.gallery.length>12)throw Error('Use at most 12 gallery photos');if(e.map_url&&!/^https:\/\//.test(e.map_url))throw Error('Map link must use HTTPS');return {id:await rpc('save_event',{p_actor:actor,p_event:e,p_categories:body.categories})};}
if(action==='cancel_event'){await rpc('cancel_event',{p_actor:actor,p_id:uuid(body.id),p_note:required(body.note,2000)});return {ok:true};}
if(action==='entry_action'){await rpc('entry_action',{p_actor:actor,p_id:uuid(body.id),p_action:body.operation,p_note:String(body.note||'').slice(0,2000)});return {ok:true};}
if(action==='review'){if(body.decision==='verified'&&body.checked!==true)throw Error('Confirm you checked the actual GCash transaction');await rpc('review',{p_payment:uuid(body.id),p_actor:actor,p_action:body.decision,p_reason:String(body.reason||'').slice(0,2000)});return {ok:true};}
if(action==='receipt'){const p=await one('payments',`id=eq.${uuid(body.id)}`);const r=await fetch(`${base}/storage/v1/object/sign/drvn-receipts/${p.receipt_path}`,{method:'POST',headers,body:JSON.stringify({expiresIn:120})});const d=await r.json();if(!r.ok)throw Error('Unable to open proof');return {url:base+'/storage/v1'+d.signedURL};}
if(action==='photo'){const path=await upload(body.file,'drvn-photos','events');return {url:`${base}/storage/v1/object/public/drvn-photos/${path}`};}
if(action==='settings'){const s=body.settings;const clean={contact_email:required(s.contact_email,200),gcash_name:required(s.gcash_name,100),gcash_number:required(s.gcash_number,30),gcash_qr:safeURL(s.gcash_qr),reservation_hours:Number(s.reservation_hours),payment_instructions:String(s.payment_instructions||'').slice(0,3000),refund_policy:required(s.refund_policy,3000)};await db('drvn_settings?id=eq.true','PATCH',clean);await db('drvn_audit','POST',{actor,action:'settings_saved'});return {ok:true};}
if(action==='email_retry'){await db(`drvn_email_queue?id=eq.${uuid(body.id)}&status=eq.failed`,'PATCH',{status:'pending',attempts:0,last_error:''});return notify();}
if(action==='send_emails'){if(!emailConfig(env).configured)throw Error('Email delivery is disabled. Configure the authorized Gmail App Password in Supabase function secrets first.');return notify();}
if(action==='export'){const regs=await db('drvn_registrations?select=id,category_id,player_name,email,partner_name,status,payment_status,amount_due&order=created_at.asc');const cats=await db('drvn_categories?select=id,tournament_id,name');return {csv:csv([['Registration ID','Category','Player','Email','Partner','Entry status','Payment status','Amount due PHP'],...regs.filter((r:any)=>!body.id||cats.some((c:any)=>c.id===r.category_id&&c.tournament_id===body.id)).map((r:any)=>[r.id,cats.find((c:any)=>c.id===r.category_id)?.name,r.player_name,r.email,r.partner_name,r.status,r.payment_status,(r.amount_due/100).toFixed(2)])])};}
throw Error('Unknown action');}
Deno.serve(async(req:Request)=>{const origin=req.headers.get('origin')||'';const allowed=[site,'http://localhost:4173','http://127.0.0.1:4173'];const cors={'Access-Control-Allow-Origin':allowed.includes(origin)?origin:site,'Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin','Cache-Control':'no-store','Content-Type':'application/json'};if(req.method==='OPTIONS')return new Response(null,{headers:cors});if(req.method!=='POST')return new Response(JSON.stringify({error:'Use POST'}),{status:405,headers:cors});try{if(origin&&!allowed.includes(origin))throw Error('Origin not allowed');if(Number(req.headers.get('content-length')||0)>3000000)throw Error('Request too large');const raw=await req.text();if(raw.length>3000000)throw Error('Request too large');const body=JSON.parse(raw);const result=await route(req,body);if(['register','payment','review','entry_action','cancel_event'].includes(body.action))EdgeRuntime.waitUntil(notify().catch(()=>{}));return new Response(JSON.stringify(result),{headers:cors});}catch(e){const message=String(e.message||'Request failed');return new Response(JSON.stringify({error:message}),{status:/Admin|session/.test(message)?401:400,headers:cors});}});
